before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libnetcdf-dev gfortran
install:
  - wget https://sourceforge.net/projects/esmf/files/ESMF_7_0_0/esmf_7_0_0_src.tar.gz/download -O /tmp/esmf_7_0_0_src.tar.gz
  - tar -xzvf /tmp/esmf_7_0_0_src.tar.gz
  - export ESMF_DIR=/tmp/esmf
  - pushd $ESMF_DIR && make && sudo make install && popd
language: fortran
script: ./configure
